from __future__ import annotations

import torch
from torch import nn

from layercake.causal_byte_models import causal_mask, run_modern_stack


class PatchGenerationDeployment(nn.Module):
    """Inference-only projection of a Layercake patch-generation path.

    The training model contains a full local byte decoder for its language-
    modeling objective plus an autoregressive long-span patch generator.  The
    ``patch`` deployment mode used by the North Star task benchmarks never
    executes the local decoder.  This wrapper registers only modules reached
    by ``generate_next_patch`` so an exported task runtime does not carry dead
    training-path weights.

    This is deliberately a scoped runtime: it supports global-context
    autoregressive patch prediction, not the full byte-LM ``forward`` API.
    """

    def __init__(self, model: nn.Module):
        super().__init__()
        if not bool(getattr(model, "patch_prediction", False)):
            raise ValueError("patch prediction must be enabled")
        if getattr(model, "patch_prediction_mode", None) != "autoregressive":
            raise ValueError("autoregressive patch prediction is required")
        if getattr(model, "patch_prediction_context", None) != "global":
            raise ValueError("only global patch-prediction context is supported")
        if int(getattr(model, "patch_encoder_layers", 0)) != 0:
            raise ValueError("patch-encoder deployment is not implemented")
        if int(getattr(model, "coarse_patch_size", 0)) != 0:
            raise ValueError("coarse-patch deployment is not implemented")

        self.patch_size = int(model.patch_size)
        self.d_model = int(model.d_model)
        self.local_decoder = "patch_generation_only"
        self.patch_prediction = True
        self.patch_prediction_mode = "autoregressive"
        self.patch_prediction_context = "global"
        self.patch_generation_bytes = int(model.patch_generation_bytes)
        self.patch_generation_context = int(model.patch_generation_context)
        self.patch_generation_copy_window = int(
            model.patch_generation_copy_window
        )
        self.ngram_buckets = int(model.ngram_buckets)
        self.patch_unit_buckets = int(model.patch_unit_buckets)
        self.modern_blocks = bool(model.modern_blocks)

        # patch_generator owns the shared byte embedding. Keeping one module
        # registration avoids duplicate deployment state entries.
        self.patch_generator = model.patch_generator
        self.patch_proj = model.patch_proj
        self.patch_pos = model.patch_pos
        self.core = model.core
        if self.ngram_buckets:
            self.bigram_emb = model.bigram_emb
            self.trigram_emb = model.trigram_emb
        if self.patch_unit_buckets:
            self.patch_unit_emb = model.patch_unit_emb

    @property
    def byte_emb(self) -> nn.Embedding:
        return self.patch_generator.byte_embedding

    @torch.inference_mode()
    def generate_next_patch(
        self,
        x: torch.Tensor,
        return_logits: bool = False,
    ) -> torch.Tensor:
        if return_logits:
            raise ValueError("patch deployment returns generated bytes only")
        batch, length = x.shape
        usable = length // self.patch_size * self.patch_size
        if usable == 0:
            raise ValueError("input must contain at least one complete patch")
        x = x[:, :usable]
        patches = x.reshape(batch, -1, self.patch_size)
        flat_byte_h = self.byte_emb(x)
        if self.ngram_buckets:
            previous = torch.cat(
                [torch.zeros_like(x[:, :1]), x[:, :-1]], dim=1
            )
            previous2 = torch.cat(
                [torch.zeros_like(x[:, :2]), x[:, :-2]], dim=1
            )
            bigram_ids = (previous * 257 + x) % self.ngram_buckets
            trigram_ids = (
                previous2 * 65537 + previous * 257 + x
            ) % self.ngram_buckets
            flat_byte_h = (
                flat_byte_h
                + self.bigram_emb(bigram_ids)
                + self.trigram_emb(trigram_ids)
            )
        byte_h = flat_byte_h.reshape(
            batch,
            -1,
            self.patch_size,
            flat_byte_h.shape[-1],
        )
        patch_features = byte_h.flatten(-2)
        if self.patch_unit_buckets:
            patch_ids = patches[:, :, 0].clone()
            for index in range(1, self.patch_size):
                patch_ids = (
                    patch_ids * 257 + patches[:, :, index]
                ) % self.patch_unit_buckets
            patch_features = torch.cat(
                [patch_features, self.patch_unit_emb(patch_ids)], dim=-1
            )
        patch_h = self.patch_proj(patch_features)
        positions = torch.arange(patch_h.shape[1], device=x.device)
        patch_h = patch_h + self.patch_pos(positions)[None]
        mask = causal_mask(patch_h.shape[1], patch_h.device)
        if self.modern_blocks:
            global_h = run_modern_stack(self.core, patch_h, mask)
        else:
            global_h = self.core(patch_h, mask=mask)
        return self.patch_generator.greedy(
            global_h[:, -1],
            (
                x[:, -self.patch_generation_context :]
                if self.patch_generation_context
                else None
            ),
            source=(
                x[:, -self.patch_generation_copy_window :]
                if self.patch_generation_copy_window
                else None
            ),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.generate_next_patch(x)

    def deployment_manifest(self) -> dict[str, object]:
        return {
            "format": "layercake-patch-generation-deployment/1",
            "scope": "global autoregressive patch generation only",
            "patch_size": self.patch_size,
            "patch_generation_bytes": self.patch_generation_bytes,
            "patch_generation_copy_window": self.patch_generation_copy_window,
            "parameter_count": sum(
                parameter.numel() for parameter in self.parameters()
            ),
        }
