"""Screen a strictly causal online mixer over frozen CountCake experts.

This is an architecture-selection probe, not a release certificate.  A mixer
may use the raw-byte context and expert likelihoods from *earlier* targets only.
The current observed target is incorporated after its mixture probability has
been recorded.  The resulting protocol is therefore valid for autoregressive
generation, where generated bytes drive the same state updates.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import sys
import time

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from layercake.count_cake import load_count_cake_bundle  # noqa: E402
from scripts.optimize_count_cake_backoff_fast import _count_statistics  # noqa: E402

try:
    from numba import njit
except ImportError as exc:  # pragma: no cover - probe dependency guard
    raise RuntimeError("this architecture probe requires numba") from exc


@njit(cache=True)
def _adaptive_bpb(
    probabilities: np.ndarray,
    contexts: np.ndarray,
    context_count: int,
    decay: float,
    eta: float,
    prior_neural_weight: float,
) -> tuple[float, float]:
    expert_count = probabilities.shape[1]
    scores = np.zeros((context_count, expert_count), dtype=np.float64)
    updates = np.zeros(context_count, dtype=np.int64)
    prior = np.zeros(expert_count, dtype=np.float64)
    if expert_count > 1 and prior_neural_weight > 0.0:
        count_weight = (1.0 - prior_neural_weight) / (expert_count - 1)
        for expert in range(expert_count - 1):
            prior[expert] = math.log(max(count_weight, 1e-12))
        prior[expert_count - 1] = math.log(max(prior_neural_weight, 1e-12))
    else:
        uniform = -math.log(expert_count)
        for expert in range(expert_count):
            prior[expert] = uniform
    nll = 0.0
    neural_weight_sum = 0.0
    for index in range(probabilities.shape[0]):
        context = contexts[index]
        maximum = -1e300
        for expert in range(expert_count):
            value = prior[expert] + eta * scores[context, expert]
            if value > maximum:
                maximum = value
        denominator = 0.0
        mixture = 0.0
        neural_numerator = 0.0
        for expert in range(expert_count):
            weight = math.exp(prior[expert] + eta * scores[context, expert] - maximum)
            denominator += weight
            mixture += weight * max(probabilities[index, expert], 1e-30)
            if expert == expert_count - 1:
                neural_numerator = weight
        mixture /= denominator
        nll -= math.log(max(mixture, 1e-30))
        neural_weight_sum += neural_numerator / denominator
        for expert in range(expert_count):
            observed = math.log(max(probabilities[index, expert], 1e-30))
            scores[context, expert] = decay * scores[context, expert] + observed
        updates[context] += 1
    return (
        nll / probabilities.shape[0] / math.log(2.0),
        neural_weight_sum / probabilities.shape[0],
    )


def _contexts(rows: torch.Tensor, start: int, order: int) -> np.ndarray:
    targets = rows[:, start:]
    if order == 0:
        return np.zeros(targets.numel(), dtype=np.int64)
    context = torch.zeros_like(targets, dtype=torch.int64)
    for offset in range(order):
        source = rows[:, start - order + offset : rows.shape[1] - order + offset]
        context.mul_(257).add_(source + 1)
    mask = (1 << (8 * order)) - 1
    return context.bitwise_and(mask).reshape(-1).cpu().numpy()


@torch.inference_mode()
def _expert_probabilities(model, rows: torch.Tensor) -> np.ndarray:
    statistics = _count_statistics(model.count_cake, rows, model.prediction_start)
    probability = statistics["unigram"]
    stages = [probability.astype(np.float32)]
    for count, total, strength in zip(
        statistics["counts"],
        statistics["totals"],
        model.count_cake.backoff_strengths,
    ):
        probability = (count + strength * probability) / (total + strength)
        stages.append(probability.astype(np.float32))
    neural_chunks = []
    for offset in range(0, rows.shape[0], 128):
        batch = rows[offset : offset + 128]
        context = model._patch_context(batch)
        targets = batch[:, model.prediction_start :].reshape(
            batch.shape[0], -1, model.patch_size
        )
        neural_log_probability, _ = model._neural_log_probs(
            context, targets, rows=batch
        )
        neural_chunks.append(neural_log_probability.reshape(-1).exp().cpu().numpy())
    neural = np.concatenate(neural_chunks).astype(np.float32)
    return np.concatenate(
        [np.stack(stages, axis=-1).reshape(-1, len(stages)), neural[:, None]],
        axis=-1,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bundle", required=True)
    parser.add_argument("--data", required=True)
    parser.add_argument("--seq-len", type=int, default=1056)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    if not torch.cuda.is_available():
        raise RuntimeError("the architecture probe requires CUDA")
    started = time.perf_counter()
    model, manifest = load_count_cake_bundle(args.bundle, device="cuda")
    model.eval()
    payload = Path(args.data).read_bytes()
    row_count = len(payload) // args.seq_len
    rows = torch.frombuffer(
        bytearray(payload[: row_count * args.seq_len]), dtype=torch.uint8
    ).reshape(row_count, args.seq_len).to(device="cuda", dtype=torch.long)
    probabilities = _expert_probabilities(model, rows)
    results = []
    for context_order in (0, 1, 2):
        contexts = _contexts(rows, model.prediction_start, context_order)
        context_count = 1 << (8 * context_order) if context_order else 1
        for decay in (0.0, 0.5, 0.9, 0.99, 0.999, 0.9999, 1.0):
            for eta in (0.05, 0.1, 0.25, 0.5, 1.0, 2.0):
                bpb, neural_weight = _adaptive_bpb(
                    probabilities,
                    contexts,
                    context_count,
                    decay,
                    eta,
                    0.15,
                )
                results.append(
                    {
                        "context_order": context_order,
                        "decay": decay,
                        "eta": eta,
                        "bpb": bpb,
                        "mean_neural_weight": neural_weight,
                    }
                )
    results.sort(key=lambda item: item["bpb"])
    report = {
        "format": "layercake-adaptive-order-mixer-probe/1",
        "status": "COMPLETE",
        "warning": (
            "architecture-selection probe; recipe grid was selected on this split "
            "and is not a held-out release result"
        ),
        "causality": {
            "score_current_target_before_update": True,
            "state_inputs": "prior expert likelihoods and preceding raw bytes only",
            "generation_equivalent": True,
        },
        "bundle": {
            "path": args.bundle,
            "parameters": manifest["parameters"],
        },
        "data": {
            "path": args.data,
            "bytes": len(payload),
            "sha256": hashlib.sha256(payload).hexdigest(),
            "scored_bytes": int(probabilities.shape[0]),
        },
        "experts": int(probabilities.shape[1]),
        "best": results[0],
        "top_results": results[:20],
        "elapsed_seconds": time.perf_counter() - started,
    }
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
