from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
from typing import Any

import torch
import torch.nn.functional as F

ROOT = Path(__file__).resolve().parents[1]

import sys

sys.path.insert(0, str(ROOT))

from layercake.causal_byte_models import CausalBytePatchLM
from layercake.portable_domain import (
    LayerCakeRuntime,
    PortableDomainDecoder,
    PortableDomainSpec,
    build_portable_artifact,
    load_portable_artifact,
)


def _load(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(path)
    return json.loads(path.read_text(encoding="utf-8"))


def _failed(gates: dict[str, bool]) -> list[str]:
    return [name for name, passed in gates.items() if not passed]


def _build_eval_bytes(length: int) -> torch.Tensor:
    seed = (
        b"LayerCake receiver transfer exactness domain. "
        b"The same portable byte-domain payload must produce identical logits, "
        b"perplexity, and generated bytes after migration into a new receiver. "
    )
    repeats = length // len(seed) + 2
    return torch.tensor(list((seed * repeats)[:length]), dtype=torch.long)


def _domain_loss(
    decoder: PortableDomainDecoder,
    stream: torch.Tensor,
    *,
    seq: int,
    batch: int,
    batches: int,
    seed: int,
) -> tuple[float, float]:
    device = next(decoder.parameters()).device
    generator = torch.Generator().manual_seed(seed)
    losses: list[float] = []
    correct = 0
    total = 0
    max_start = stream.numel() - seq - 1
    if max_start <= 0:
        raise ValueError("eval stream is too short")
    with torch.no_grad():
        for _ in range(batches):
            starts = torch.randint(0, max_start, (batch,), generator=generator)
            rows = torch.stack([stream[i : i + seq + 1] for i in starts]).to(device)
            x = rows[:, :-1]
            y = rows[:, 1:]
            logits = decoder(x)
            losses.append(F.cross_entropy(logits.flatten(0, 1), y.flatten()).item())
            correct += (logits.argmax(dim=-1) == y).sum().item()
            total += y.numel()
    loss = sum(losses) / len(losses)
    return loss, correct / max(total, 1)


def _train_decoder(
    decoder: PortableDomainDecoder,
    stream: torch.Tensor,
    *,
    seq: int,
    batch: int,
    steps: int,
    lr: float,
) -> float:
    if steps <= 0:
        return 0.0
    decoder.train()
    optimizer = torch.optim.AdamW(decoder.parameters(), lr=lr)
    generator = torch.Generator().manual_seed(60630)
    max_start = stream.numel() - seq - 1
    started = torch.cuda.Event(enable_timing=True) if torch.cuda.is_available() else None
    ended = torch.cuda.Event(enable_timing=True) if torch.cuda.is_available() else None
    import time

    wall_start = time.perf_counter()
    if started is not None:
        started.record()
    device = next(decoder.parameters()).device
    for _ in range(steps):
        starts = torch.randint(0, max_start, (batch,), generator=generator)
        rows = torch.stack([stream[i : i + seq + 1] for i in starts]).to(device)
        x = rows[:, :-1]
        y = rows[:, 1:]
        logits = decoder(x)
        loss = F.cross_entropy(logits.flatten(0, 1), y.flatten())
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(decoder.parameters(), 1.0)
        optimizer.step()
    if ended is not None:
        ended.record()
        torch.cuda.synchronize()
    decoder.eval()
    return time.perf_counter() - wall_start


def _make_distinct_core(seed: int, d_model: int, d_abi: int, layers: int) -> CausalBytePatchLM:
    torch.manual_seed(seed)
    model = CausalBytePatchLM(
        patch_size=2,
        d_byte=16,
        d_model=d_model,
        d_abi=d_abi,
        layers=layers,
        heads=4,
        max_patches=64,
        local_decoder="conv",
        conv_layers=1,
        local_width=d_model,
        local_window=16,
        direct_global_context=True,
    )
    model.eval()
    return model


def verify(
    strict_certificate: Path,
    output: Path,
    *,
    eval_bytes: int,
    eval_batches: int,
    generation_bytes: int,
    train_steps: int,
) -> dict[str, Any]:
    strict = _load(strict_certificate)
    strict_scale_rows = strict.get("scales", [])
    strict_receiver_scales_pass = bool(strict.get("status") == "PASS") and all(
        row.get("status") == "PASS" for row in strict_scale_rows
    )

    torch.manual_seed(20260630)
    source_decoder = PortableDomainDecoder(
        feature_width=32,
        hidden_width=64,
        architecture="byte_gru",
        embedding_width=16,
    )
    # Deterministically perturb the payload so the copy test is not an all-zero/no-op path.
    with torch.no_grad():
        for index, parameter in enumerate(source_decoder.parameters()):
            parameter.add_(torch.sin(torch.arange(parameter.numel()).reshape_as(parameter)) * (0.001 + index * 0.0001))
    spec = PortableDomainSpec(
        "micro-transfer-domain",
        feature_width=32,
        hidden_width=64,
        architecture="byte_gru",
        embedding_width=16,
    )
    artifact = build_portable_artifact(source_decoder, spec)
    source_spec, loaded_source = load_portable_artifact(artifact, "cpu")
    target_spec, loaded_target = load_portable_artifact(artifact, "cpu")

    stream = _build_eval_bytes(eval_bytes)
    train_stream = _build_eval_bytes(max(eval_bytes * 4, 32768))
    seq = 64
    train_seconds = _train_decoder(
        source_decoder,
        train_stream,
        seq=seq,
        batch=8,
        steps=train_steps,
        lr=2e-3,
    )
    artifact = build_portable_artifact(source_decoder, spec, training={"steps": train_steps, "elapsed_seconds": train_seconds})
    source_spec, loaded_source = load_portable_artifact(artifact, "cpu")
    target_spec, loaded_target = load_portable_artifact(artifact, "cpu")
    source_loss, source_acc = _domain_loss(
        loaded_source,
        stream,
        seq=seq,
        batch=8,
        batches=eval_batches,
        seed=7001,
    )
    target_loss, target_acc = _domain_loss(
        loaded_target,
        stream,
        seq=seq,
        batch=8,
        batches=eval_batches,
        seed=7001,
    )
    with torch.no_grad():
        x = stream[:seq].unsqueeze(0)
        source_logits = loaded_source(x)
        target_logits = loaded_target(x)
        max_logit_diff = (source_logits - target_logits).abs().max().item()

    source_runtime = LayerCakeRuntime(_make_distinct_core(11, d_model=64, d_abi=32, layers=0))
    target_runtime = LayerCakeRuntime(_make_distinct_core(99, d_model=96, d_abi=32, layers=1))
    source_runtime.install_portable_domain(artifact)
    target_runtime.install_portable_domain(artifact)
    prompt = stream[:seq].unsqueeze(0)
    source_generation = source_runtime.generate(
        prompt,
        max_new_bytes=generation_bytes,
        domain_id=source_spec.domain_id,
        context_bytes=seq,
    )
    target_generation = target_runtime.generate(
        prompt,
        max_new_bytes=generation_bytes,
        domain_id=target_spec.domain_id,
        context_bytes=seq,
    )
    generated_equal = torch.equal(source_generation, target_generation)
    generated_bytes = bytes(source_generation[0].tolist())

    ppl_ratio = math.exp(target_loss) / max(math.exp(source_loss), 1e-12)
    gates = {
        "strict_core_receiver_scales_pass": strict_receiver_scales_pass,
        "source_and_receiver_specs_equal": source_spec == target_spec,
        "source_and_receiver_payload_hash_equal": artifact["payload_hash"]
        == build_portable_artifact(loaded_target, target_spec)["payload_hash"],
        "transfer_ppl_ratio_exact": ppl_ratio == 1.0,
        "transfer_loss_exact": target_loss == source_loss,
        "transfer_top1_accuracy_exact": target_acc == source_acc,
        "transfer_max_logit_diff_exact": max_logit_diff == 0.0,
        "transfer_generation_exact": generated_equal,
        "domain_payload_bpb_below_uniform": (source_loss / math.log(2)) < 8.0,
        "domain_payload_top1_above_zero": source_acc > 0.0,
    }
    result = {
        "status": "PASS" if all(gates.values()) else "FAIL",
        "scope": (
            "Receiver-after-transfer exactness joined to the strict 1M-10M "
            "micro dominance certificate. This proves byte-domain payload "
            "migration is exact across distinct receiver cores; it is not yet "
            "a large-scale game-domain adapter comparison."
        ),
        "strict_certificate": str(
            strict_certificate.relative_to(ROOT)
            if strict_certificate.is_relative_to(ROOT)
            else strict_certificate
        ),
        "required_gates": gates,
        "failed": _failed(gates),
        "metrics": {
            "eval_bytes": eval_bytes,
            "eval_batches": eval_batches,
            "domain_train_steps": train_steps,
            "domain_train_seconds": train_seconds,
            "source_loss": source_loss,
            "target_loss": target_loss,
            "source_ppl": math.exp(source_loss),
            "target_ppl": math.exp(target_loss),
            "transfer_ppl_ratio": ppl_ratio,
            "source_top1_accuracy": source_acc,
            "target_top1_accuracy": target_acc,
            "transfer_max_logit_diff": max_logit_diff,
            "generated_sha256": hashlib.sha256(generated_bytes).hexdigest(),
            "source_core_signature": "seed11/d_model64/layers0",
            "receiver_core_signature": "seed99/d_model96/layers1",
        },
        "claim_boundary": (
            "PASS supports exact receiver migration for the portable byte-domain "
            "payload plus strict micro core dominance. It does not by itself "
            "claim multi-domain game readiness or large-scale transformer "
            "obsolescence."
        ),
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, indent=2, sort_keys=True), encoding="utf-8")
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--strict-certificate",
        default="results/micro_strict_speed_probe_1m10m_strict_certificate.json",
    )
    parser.add_argument(
        "--output",
        default="results/micro_receiver_transfer_strict_certificate.json",
    )
    parser.add_argument("--eval-bytes", type=int, default=8192)
    parser.add_argument("--eval-batches", type=int, default=8)
    parser.add_argument("--generation-bytes", type=int, default=32)
    parser.add_argument("--train-steps", type=int, default=120)
    args = parser.parse_args()
    strict_certificate = Path(args.strict_certificate)
    if not strict_certificate.is_absolute():
        strict_certificate = ROOT / strict_certificate
    output = Path(args.output)
    if not output.is_absolute():
        output = ROOT / output
    result = verify(
        strict_certificate,
        output,
        eval_bytes=args.eval_bytes,
        eval_batches=args.eval_batches,
        generation_bytes=args.generation_bytes,
        train_steps=args.train_steps,
    )
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0 if result["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
